"""Generate the deterministic Agent02 Step-1 public-contract fixture."""

from __future__ import annotations

import argparse
from datetime import UTC, datetime
from pathlib import Path

from material_agent.ml_screening.adapters import (
    FakeMLModelAdapter,
    FakeMLWorker,
)
from material_agent.ml_screening.models import (
    AGENT02_CONTRACT_VERSION,
    ArtifactPointer,
    ArtifactRef,
    CandidateProperty,
    EvidenceLevel,
    MLCandidateInput,
    MLCandidateManifestRecord,
    MLCandidateResultSummary,
    MLDecision,
    MLScreeningRequest,
    MLStagePlan,
    MLStageResultEnvelope,
    NativeStageStatus,
    StructureRef,
    WorkerRequest,
    WorkerResponse,
)
from material_agent.ml_screening.planner import build_ml_stage_plan
from material_agent.ml_screening.requirement import (
    requirement_view_from_payload,
)
from material_agent.ml_screening.resources import (
    default_policy,
    fake_health_snapshot,
    fake_model_card,
    fake_model_spec,
    fake_registry,
)
from material_agent.retrieval.storage import LocalArtifactStore

FIXED_TIME = datetime(2026, 7, 26, 0, 0, tzinfo=UTC)
README_TEXT = """# Agent02 v1 contract fixture

Generated by `scripts/generate_agent02_contract_fixture.py`.

This fixture uses `FakeMLModelAdapter` and `FakeMLWorker`. Every generated
property is marked `is_mock=true`, remains `L1_RETRIEVED`, and must not be
presented as scientific ML evidence.

The frozen worker request processes one candidate, contains only root-relative
I/O paths, and deliberately has no JSON field for the trusted artifact root.
The fixed fixture clock falls inside the fake health snapshot validity window.
"""


def generate(output_root: Path, fixture_root: Path) -> None:
    store = LocalArtifactStore(output_root)
    store.write_text("README.md", README_TEXT, "text/markdown")
    requirement_payload = store_source_requirement(fixture_root)
    requirement = requirement_view_from_payload(requirement_payload)
    policy = default_policy()
    model_card = fake_model_card()
    model = fake_model_spec()
    registry = fake_registry()
    health = fake_health_snapshot()

    requirement_ref = store.write_json(
        "requirements/requirement.v1.json",
        requirement_payload,
    )
    policy_ref = store.write_json(
        "policies/ml-screening-policy-v1.json",
        policy.model_dump(mode="json"),
    )
    card_ref = store.write_json(
        "models/fake-model-card.json",
        model_card.model_dump(mode="json"),
    )
    checkpoint_ref = store.write_bytes(
        "models/fake-checkpoint.txt",
        b"agent02-fake-checkpoint-v1",
        "text/plain",
    )
    lock_ref = store.write_bytes(
        "models/fake-lock.txt",
        b"agent02-fake-package-lock-v1",
        "text/plain",
    )
    assert card_ref.sha256 == model.model_card_sha256
    assert checkpoint_ref.sha256 == model.checkpoint_sha256
    assert lock_ref.sha256 == model.package_lock_sha256
    registry_ref = store.write_json(
        "models/model-registry-v1.json",
        registry.model_dump(mode="json"),
    )
    health_ref = store.write_json(
        "models/fake-health.json",
        health.model_dump(mode="json"),
    )

    structure_ref = store.write_text(
        "upstream/str_contract_si_o.cif",
        (
            "data_SiO2_contract_fixture\n"
            "_chemical_formula_sum 'Si O2'\n"
            "_cell_length_a 5.0\n"
            "_cell_length_b 5.0\n"
            "_cell_length_c 5.0\n"
        ),
        "chemical/x-cif",
    )
    upstream_ref = store.write_jsonl(
        "upstream/agent01-candidate-manifest.jsonl",
        [
            {
                "schema_version": "agent01-contract-v1",
                "candidate_id": "cand_contract_si_o",
                "structure_id": "str_contract_si_o",
                "structure_artifact_uri": structure_ref.uri,
                "structure_artifact_sha256": structure_ref.sha256,
                "publication_rank": 1,
                "decision": "PASS",
            }
        ],
    )
    candidate = MLCandidateInput(
        candidate_id="cand_contract_si_o",
        upstream_manifest_uri=upstream_ref.uri,
        upstream_manifest_sha256=upstream_ref.sha256,
        formula="SiO2",
        elements=["O", "Si"],
        num_sites=3,
        publication_rank=1,
        upstream_decision=MLDecision.PASS,
        upstream_evidence_level=EvidenceLevel.L1_RETRIEVED,
        properties=[
            CandidateProperty(
                name="band_gap",
                value=0.8,
                unit="eV",
            ),
            CandidateProperty(
                name="energy_above_hull",
                value=0.02,
                unit="eV/atom",
            ),
            CandidateProperty(
                name="is_metal",
                value=False,
                unit="dimensionless",
            ),
        ],
        source_structure=StructureRef(
            structure_id="str_contract_si_o",
            uri=structure_ref.uri,
            sha256=structure_ref.sha256,
            num_sites=3,
            elements=["O", "Si"],
            dimensionality=3,
            is_periodic=True,
            is_inorganic=True,
            parseable=True,
            ase_compatible=True,
            has_finite_values=True,
            positive_volume=True,
            minimum_distance_angstrom=1.6,
            hash_verified=True,
        ),
    )
    input_ref = store.write_json(
        "plans/run-agent02-contract/stages/ml/attempt-1.input.json",
        {
            "schema_version": "orchestrator-p0.2-stage-input-v1",
            "run_id": "run-agent02-contract",
            "requirement": {
                "uri": requirement_ref.uri,
                "sha256": requirement_ref.sha256,
            },
            "candidate_manifest": {
                "uri": upstream_ref.uri,
                "sha256": upstream_ref.sha256,
            },
        },
    )
    request = MLScreeningRequest()
    plan = build_ml_stage_plan(
        project_id="project-agent02-contract",
        run_id="run-agent02-contract",
        requirement_revision=requirement.revision,
        attempt=1,
        orchestrator_input_snapshot=_pointer(input_ref),
        requirement_artifact=_pointer(requirement_ref),
        candidate_manifest_artifact=_pointer(upstream_ref),
        stage_request_artifact=None,
        policy_artifact=_pointer(policy_ref),
        registry_artifact=_pointer(registry_ref),
        health_artifact=_pointer(health_ref),
        requirement=requirement,
        candidates=[candidate],
        request=request,
        policy=policy,
        registry=registry,
        health=health,
        created_at=FIXED_TIME,
    )
    plan_ref = store.write_json(
        "plans/run-agent02-contract/stages/ml/attempt-1.native.json",
        plan.model_dump(mode="json"),
    )

    adapter = FakeMLModelAdapter(model=model, health=health)
    worker = FakeMLWorker(adapter=adapter, policy=policy)
    artifacts = worker.generate_artifacts(plan)
    request = worker.request_for_candidate(
        plan,
        plan.inference_candidate_ids[0],
        input_root_relative_path=structure_ref.uri.removeprefix(
            "artifact://"
        ),
        input_size_bytes=structure_ref.size_bytes,
    )
    response = worker.run(request)
    manifest_ref = store.write_jsonl(
        (
            "stages/agent02/run-agent02-contract/attempt-1/"
            "ml-candidate-manifest.jsonl"
        ),
        [
            record.model_dump(mode="json")
            for record in artifacts.manifest
        ],
    )
    report_ref = store.write_text(
        "stages/agent02/run-agent02-contract/attempt-1/report.md",
        artifacts.report_markdown,
        "text/markdown",
    )
    request_ref = store.write_json(
        (
            "stages/agent02/run-agent02-contract/attempt-1/"
            "fake-worker-request.json"
        ),
        request.model_dump(mode="json"),
    )
    worker_ref = store.write_json(
        (
            "stages/agent02/run-agent02-contract/attempt-1/"
            "fake-worker-response.json"
        ),
        response.model_dump(mode="json"),
    )
    result = MLStageResultEnvelope(
        project_id=plan.project_id,
        run_id=plan.run_id,
        status=NativeStageStatus.SUCCEEDED,
        operation_key=(
            "project-agent02-contract:run-agent02-contract:ml:"
            "attempt-1:fixture"
        ),
        plan=_pointer(plan_ref),
        execution_identity=plan.execution_identity,
        candidate_manifest=_artifact(manifest_ref),
        output_artifacts=[
            _artifact(manifest_ref),
            _artifact(report_ref),
            _artifact(request_ref),
            _artifact(worker_ref),
        ],
        candidate_ids=[
            record.candidate.candidate_id for record in artifacts.manifest
        ],
        candidate_summaries=[
            MLCandidateResultSummary.from_result(record.candidate)
            for record in artifacts.manifest
        ],
        status_counts={"UNCERTAIN": len(artifacts.manifest)},
        warnings=response.warnings,
        started_at=FIXED_TIME,
        finished_at=FIXED_TIME,
        provenance={
            "fixture_kind": "deterministic mock",
        },
    )
    result.validate_against(
        plan=plan,
        manifest=artifacts.manifest,
        operation_key=result.operation_key,
    )
    result_ref = store.write_json(
        (
            "stages/agent02/run-agent02-contract/attempt-1/"
            "stage-result.json"
        ),
        result.model_dump(mode="json"),
    )

    schemas = [
        store.write_json(
            "schemas/ml-stage-plan.schema.json",
            MLStagePlan.model_json_schema(),
        ),
        store.write_json(
            "schemas/ml-candidate-manifest-record.schema.json",
            MLCandidateManifestRecord.model_json_schema(),
        ),
        store.write_json(
            "schemas/ml-stage-result-envelope.schema.json",
            MLStageResultEnvelope.model_json_schema(),
        ),
        store.write_json(
            "schemas/worker-request.schema.json",
            WorkerRequest.model_json_schema(),
        ),
        store.write_json(
            "schemas/worker-response.schema.json",
            WorkerResponse.model_json_schema(),
        ),
    ]
    store.write_json(
        "fixture_manifest.json",
        {
            "contract_version": AGENT02_CONTRACT_VERSION,
            "model_card": card_ref.model_dump(mode="json"),
            "policy": policy_ref.model_dump(mode="json"),
            "registry": registry_ref.model_dump(mode="json"),
            "health": health_ref.model_dump(mode="json"),
            "native_plan": plan_ref.model_dump(mode="json"),
            "candidate_manifest": manifest_ref.model_dump(mode="json"),
            "report": report_ref.model_dump(mode="json"),
            "worker_request": request_ref.model_dump(mode="json"),
            "worker_response": worker_ref.model_dump(mode="json"),
            "stage_result": result_ref.model_dump(mode="json"),
            "schemas": [
                schema.model_dump(mode="json") for schema in schemas
            ],
        },
    )


def store_source_requirement(fixture_root: Path) -> dict:
    import json

    return json.loads(
        (fixture_root / "requirement.si-o.json").read_text(encoding="utf-8")
    )


def _pointer(ref) -> ArtifactPointer:
    return ArtifactPointer(uri=ref.uri, sha256=ref.sha256)


def _artifact(ref) -> ArtifactRef:
    return ArtifactRef.model_validate(ref.model_dump(mode="json"))


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("tests/fixtures/contracts/agent02-v1"),
    )
    parser.add_argument(
        "--fixture-root",
        type=Path,
        default=Path("tests/fixtures"),
    )
    arguments = parser.parse_args()
    generate(arguments.output, arguments.fixture_root)


if __name__ == "__main__":
    main()
